-- Juventus F.C. — initial schema
--
-- Conventions
--   * ids are opaque text (prefix + random) generated by the API, never by the client
--   * timestamps are ISO 8601 strings in UTC (created_at / updated_at on every entity)
--   * dates without time are YYYY-MM-DD, matching what the UI already formats
--   * every club-owned row carries club_id so a second organisation never requires a rewrite
--   * relations are foreign keys with explicit ON DELETE behaviour

-- ============================================================ organisation

CREATE TABLE clubs (
  id             TEXT PRIMARY KEY,
  official_name  TEXT NOT NULL,
  short_name     TEXT NOT NULL,
  city           TEXT,
  state          TEXT,
  country        TEXT NOT NULL DEFAULT 'Brasil',
  founded_year   TEXT,
  venue          TEXT,
  address        TEXT,
  phone          TEXT,
  email          TEXT,
  website        TEXT,
  social         TEXT,
  crest_key      TEXT,               -- future R2 object key
  primary_color  TEXT,
  secondary_color TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

CREATE TABLE club_settings (
  club_id             TEXT PRIMARY KEY REFERENCES clubs(id) ON DELETE CASCADE,
  default_monthly_fee REAL NOT NULL DEFAULT 0,
  default_due_day     INTEGER NOT NULL DEFAULT 10 CHECK (default_due_day BETWEEN 1 AND 31),
  payment_methods     TEXT NOT NULL DEFAULT '[]',   -- JSON array of strings
  currency            TEXT NOT NULL DEFAULT 'BRL',
  season              TEXT,
  low_stock_alerts    INTEGER NOT NULL DEFAULT 1,
  due_reminders       INTEGER NOT NULL DEFAULT 1,
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL
);

CREATE TABLE teams (
  id         TEXT PRIMARY KEY,
  club_id    TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (club_id, name)
);
CREATE INDEX idx_teams_club ON teams(club_id);

-- ================================================================= people

-- A person exists once. Roles below reference this row instead of copying it.
CREATE TABLE people (
  id         TEXT PRIMARY KEY,
  club_id    TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  full_name  TEXT NOT NULL,
  nickname   TEXT,
  birth_date TEXT,
  phone      TEXT,
  email      TEXT,
  document   TEXT,
  address    TEXT,
  city       TEXT,
  status     TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo', 'inativo')),
  notes      TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX idx_people_club ON people(club_id);
CREATE INDEX idx_people_name ON people(club_id, full_name);

CREATE TABLE players (
  id                 TEXT PRIMARY KEY,
  club_id            TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  person_id          TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  team_id            TEXT REFERENCES teams(id) ON DELETE SET NULL,
  shirt_number       INTEGER,
  position           TEXT NOT NULL,
  secondary_position TEXT,
  joined_at          TEXT,
  monthly_fee        REAL NOT NULL DEFAULT 0,
  due_day            INTEGER NOT NULL DEFAULT 10 CHECK (due_day BETWEEN 1 AND 31),
  status             TEXT NOT NULL DEFAULT 'ativo'
                     CHECK (status IN ('ativo','lesionado','suspenso','afastado','inativo')),
  notes              TEXT,
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL,
  -- one squad record per person; a person may still be board member and staff
  UNIQUE (person_id)
);
CREATE INDEX idx_players_club ON players(club_id);
CREATE INDEX idx_players_team ON players(team_id);

CREATE TABLE board_members (
  id         TEXT PRIMARY KEY,
  club_id    TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  person_id  TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  role       TEXT NOT NULL,
  start_date TEXT,
  end_date   TEXT,
  status     TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','encerrado')),
  notes      TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX idx_board_club ON board_members(club_id);
CREATE INDEX idx_board_person ON board_members(person_id);

CREATE TABLE staff_members (
  id         TEXT PRIMARY KEY,
  club_id    TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  person_id  TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  role       TEXT NOT NULL,
  specialty  TEXT,
  team_id    TEXT REFERENCES teams(id) ON DELETE SET NULL,
  start_date TEXT,
  status     TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','inativo')),
  notes      TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX idx_staff_club ON staff_members(club_id);
CREATE INDEX idx_staff_person ON staff_members(person_id);

-- ====================================================== access & sessions

-- An account is optional for a person and is a separate concept from it.
CREATE TABLE accounts (
  id            TEXT PRIMARY KEY,
  club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  person_id     TEXT NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  username      TEXT NOT NULL COLLATE NOCASE,
  password_hash TEXT NOT NULL,          -- pbkdf2$sha256$<iterations>$<salt>$<hash>
  status        TEXT NOT NULL DEFAULT 'ativo' CHECK (status IN ('ativo','suspenso')),
  is_owner      INTEGER NOT NULL DEFAULT 0,
  last_login_at TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
CREATE UNIQUE INDEX idx_accounts_username ON accounts(username);
CREATE INDEX idx_accounts_person ON accounts(person_id);

-- Granular capabilities: "<module>.<action>", never a rigid role.
CREATE TABLE account_permissions (
  account_id TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  permission TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (account_id, permission)
);

CREATE TABLE sessions (
  id           TEXT PRIMARY KEY,
  account_id   TEXT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  token_hash   TEXT NOT NULL,           -- SHA-256 of the cookie token; the token itself is never stored
  created_at   TEXT NOT NULL,
  expires_at   TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  revoked_at   TEXT,
  user_agent   TEXT
);
CREATE UNIQUE INDEX idx_sessions_token ON sessions(token_hash);
CREATE INDEX idx_sessions_account ON sessions(account_id);

-- ================================================================ football

CREATE TABLE competitions (
  id         TEXT PRIMARY KEY,
  club_id    TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  season     TEXT,
  organizer  TEXT,
  team_id    TEXT REFERENCES teams(id) ON DELETE SET NULL,
  status     TEXT NOT NULL DEFAULT 'planejado'
             CHECK (status IN ('planejado','em andamento','encerrado')),
  format     TEXT,
  notes      TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX idx_competitions_club ON competitions(club_id);

CREATE TABLE matches (
  id             TEXT PRIMARY KEY,
  club_id        TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  match_date     TEXT NOT NULL,
  match_time     TEXT NOT NULL DEFAULT '15:00',
  opponent       TEXT NOT NULL,
  location       TEXT,
  venue          TEXT NOT NULL DEFAULT 'mandante' CHECK (venue IN ('mandante','visitante')),
  competition_id TEXT REFERENCES competitions(id) ON DELETE SET NULL,
  team_id        TEXT REFERENCES teams(id) ON DELETE SET NULL,
  status         TEXT NOT NULL DEFAULT 'agendado'
                 CHECK (status IN ('agendado','confirmado','encerrado','adiado','cancelado')),
  goals_for      INTEGER,
  goals_against  INTEGER,
  notes          TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);
CREATE INDEX idx_matches_club_date ON matches(club_id, match_date);
CREATE INDEX idx_matches_competition ON matches(competition_id);

CREATE TABLE trainings (
  id             TEXT PRIMARY KEY,
  club_id        TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  training_date  TEXT NOT NULL,
  training_time  TEXT NOT NULL DEFAULT '19:30',
  location       TEXT,
  team_id        TEXT REFERENCES teams(id) ON DELETE SET NULL,
  responsible_id TEXT REFERENCES staff_members(id) ON DELETE SET NULL,
  type           TEXT NOT NULL DEFAULT 'Técnico',
  status         TEXT NOT NULL DEFAULT 'agendado'
                 CHECK (status IN ('agendado','realizado','cancelado')),
  notes          TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);
CREATE INDEX idx_trainings_club_date ON trainings(club_id, training_date);

CREATE TABLE training_participants (
  training_id TEXT NOT NULL REFERENCES trainings(id) ON DELETE CASCADE,
  player_id   TEXT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  present     INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (training_id, player_id)
);

CREATE TABLE lineups (
  id         TEXT PRIMARY KEY,
  club_id    TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  match_id   TEXT NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  formation  TEXT NOT NULL DEFAULT '4-3-3',
  notes      TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (match_id)
);
CREATE INDEX idx_lineups_club ON lineups(club_id);

CREATE TABLE lineup_entries (
  lineup_id    TEXT NOT NULL REFERENCES lineups(id) ON DELETE CASCADE,
  player_id    TEXT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  slot         TEXT NOT NULL DEFAULT 'titular' CHECK (slot IN ('titular','reserva')),
  position     TEXT,
  shirt_number INTEGER,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (lineup_id, player_id)
);

CREATE TABLE lineup_staff (
  lineup_id TEXT NOT NULL REFERENCES lineups(id) ON DELETE CASCADE,
  staff_id  TEXT NOT NULL REFERENCES staff_members(id) ON DELETE CASCADE,
  PRIMARY KEY (lineup_id, staff_id)
);

-- =============================================================== financial

CREATE TABLE monthly_dues (
  id              TEXT PRIMARY KEY,
  club_id         TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  player_id       TEXT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  reference_month TEXT NOT NULL,          -- YYYY-MM
  due_date        TEXT NOT NULL,
  expected_amount REAL NOT NULL DEFAULT 0,
  paid_amount     REAL NOT NULL DEFAULT 0,
  paid_at         TEXT,
  method          TEXT,
  status          TEXT NOT NULL DEFAULT 'pendente'
                  CHECK (status IN ('pago','pendente','parcial','atrasado')),
  notes           TEXT,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL,
  UNIQUE (player_id, reference_month)
);
CREATE INDEX idx_dues_club_month ON monthly_dues(club_id, reference_month);
CREATE INDEX idx_dues_status ON monthly_dues(club_id, status);

CREATE TABLE income_entries (
  id          TEXT PRIMARY KEY,
  club_id     TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  entry_date  TEXT NOT NULL,
  description TEXT NOT NULL,
  category    TEXT NOT NULL DEFAULT 'Outros',
  source      TEXT,
  amount      REAL NOT NULL CHECK (amount >= 0),
  method      TEXT,
  responsible TEXT,
  notes       TEXT,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX idx_income_club_date ON income_entries(club_id, entry_date);

CREATE TABLE expense_entries (
  id          TEXT PRIMARY KEY,
  club_id     TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  entry_date  TEXT NOT NULL,
  description TEXT NOT NULL,
  category    TEXT NOT NULL DEFAULT 'Outros',
  supplier    TEXT,
  amount      REAL NOT NULL CHECK (amount >= 0),
  method      TEXT,
  responsible TEXT,
  notes       TEXT,
  created_at  TEXT NOT NULL,
  updated_at  TEXT NOT NULL
);
CREATE INDEX idx_expense_club_date ON expense_entries(club_id, entry_date);

-- =============================================================== inventory

CREATE TABLE inventory_items (
  id           TEXT PRIMARY KEY,
  club_id      TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  category     TEXT NOT NULL DEFAULT 'Outros',
  quantity     REAL NOT NULL DEFAULT 0,
  unit         TEXT NOT NULL DEFAULT 'un',
  min_quantity REAL NOT NULL DEFAULT 0,
  location     TEXT,
  notes        TEXT,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX idx_inventory_club ON inventory_items(club_id);

-- quantity on inventory_items is the running balance, always written in the
-- same transaction as the movement that changes it.
CREATE TABLE inventory_movements (
  id            TEXT PRIMARY KEY,
  club_id       TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  item_id       TEXT NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  type          TEXT NOT NULL CHECK (type IN ('entrada','saida','ajuste')),
  quantity      REAL NOT NULL,
  movement_date TEXT NOT NULL,
  responsible   TEXT,
  reason        TEXT,
  notes         TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
CREATE INDEX idx_movements_club_date ON inventory_movements(club_id, movement_date);
CREATE INDEX idx_movements_item ON inventory_movements(item_id);

-- ================================================================== audit

CREATE TABLE activity_log (
  id          TEXT PRIMARY KEY,
  club_id     TEXT NOT NULL REFERENCES clubs(id) ON DELETE CASCADE,
  account_id  TEXT REFERENCES accounts(id) ON DELETE SET NULL,
  actor_name  TEXT NOT NULL,
  kind        TEXT NOT NULL,     -- financeiro | elenco | futebol | estoque | sistema
  title       TEXT NOT NULL,
  detail      TEXT,
  entity_type TEXT,
  entity_id   TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX idx_activity_club_date ON activity_log(club_id, created_at DESC);
